import numpy as np
from sklearn import metrics

'''
Evaluation metrics for COMBSS
'''

""" Computes the evaluation metrics for COMBSS.

	Parameters
	----------
	data_X : array-like of shape (n_samples, n_covariates)
        The design matrix, where `n_samples` is the number of samples observed
        and `n_covariates` is the number of covariates measured in each sample.

    beta_true : array-like of shape (n_covariates, 1)
        The true values of beta used in the generation of data.

    beta_pred : array-like of shape (n_covariates, 1)
        The predicted values of beta generated by COMBSS.


	Returns
	-------
	pe : float
        The model's relative prediction error, expressed as a ratio of the root of the model's .. 

    MCC : float
        The Matthew's Correlation Coefficient of the particular model.

    accuracy : float
        The accuracy of the particular model, calculated as the rate at which the model
        correctly predicts wheter or not a predictor is correctly chosen to be selected or
        rejected from the best subset. This is calculated as a rate and expressed as a 
        decimal from 0 to 1.

    sensitivity : float
        The ability of the particular model to correctly determine the inclusion of 
        predictors that belong in the best subset, calculated as a rate and expressed 
        as a decimal from 0 to 1.

    specificity : 
        The ability of the particular model to correctly determine the rejection of 
        predictors that do not belong in the best subset, calculated as a rate and expressed 
        as a decimal from 0 to 1.

    f1_score :
        The F1-Score of the particular model.

    precision :
        The ability of the particular model to retrieve the correct subset of predictors, 
        calculated as a rate and expressed as a decimal from 0 to 1.

	Notes
	-----
	
"""
def performance_metrics(data_X, beta_true, beta_pred):
    """
    Function for computing performance metrics.
    """
  
    s_true = [beta_true != 0][0]
    s_pred = [beta_pred != 0][0]
    c_matrix = metrics.confusion_matrix(s_true, s_pred)
    
    TN = c_matrix[0, 0]
    FN = c_matrix[1, 0]
    FP = c_matrix[0, 1]
    TP = c_matrix[1, 1]
    
    
    accuracy = (TP + TN)/(TP + TN + FP + FN)
    sensitivity = TP/(TP + FN)
    specificity = TN/(TN + FP)
    
    
    if (sum(s_pred) == 0):
        pe = 1
        precision = 'NA'
        MCC = 'NA'
    else:
        Xbeta_true = data_X@beta_true
        pe = np.square(Xbeta_true - data_X@beta_pred).mean()/np.square(Xbeta_true).mean()        
        precision =  TP/(TP + FP)
        # print('Pre + Sens:', precision + sensitivity)
        MCC = (TP*TN-FP*FN)/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    if TP == 0:
        f1_score = 0.0
    else:
        f1_score = TP/(TP + (FP + FN)/2)
        #f1_score = (2*precision*sensitivity)/(precision + sensitivity)
    
    # accuracy = round(accuracy, 4)
    # sensitivity = round(sensitivity, 4)
    # specificity = round(specificity, 4)
    # pe = round(pe, 4)
    # precision = round(precision, 4)
    # f1_score = round(f1_score, 4)
    # MCC = round(MCC, 4)
    
    #print(pe, MCC, accuracy, sensitivity, specificity, f1_score, precision)
        
    return [pe, MCC, accuracy, sensitivity, specificity, f1_score, precision]
