import numpy as np
import sys


def gen_beta0(p, k0, case):

    """ Generates an array of true beta parameters.

	Parameters
	----------
	p : integer
        The number of features (i.e., columns of the design matrix X).

    k0 : int
       The number of non-zero elements in the coefficient vector beta.

    case : int
        The specific type of beta desired to be generated, such that
        - case 0: k0 non-zero coefficients of true beta are placed at equl distance
        - case 1: The first k0 components of beta are equal to 1 and all others are equal to 0
        - case 2: the first k0 components of beta decrease as beta_i = 0.5^i for i = 0, 1, ...., k0, 
          and all other elements are equal to 0
	
          
    Returns
	-------
    beta0 : array-like of floats.
        The true values of beta generated by this function.

    S0: array-like of integers.
        The indices of non-zero coefficients of beta i.e., the true model.
    """ 
  
    if k0 > p:
        print("Error: k0 is greater than p")
        print(sys.path)
        sys.tracebacklimit = 1
        raise ValueError()
        
    beta0 = np.zeros(p)
    if case == 0:
        gap = int(p/k0)
        S0 = np.array([i*gap for i in range(k0)])  #indices of non-zero coefficients (i.e., true model)
        beta0[S0] = 1
        return beta0, S0
    
    elif case == 1:
        S0 = np.arange(k0)
        beta0[S0] = 1
        return beta0, S0

    elif case == 2:
        S0 = np.arange(k0)
        beta0[S0] = np.array([0.5**i for i in S0])
        return beta0, S0



def cov_X(p, corr):

    """ Generates the covariance matrix, cov of data.

	Parameters
	----------
	p : integer
        The number of features (i.e., columns of the design matrix X).

    corr : float
       The correlation coefficient such that cov[i, j] = corr^{|i - j|}

       
	Returns
	-------
    cov : array-like of floats of shape (n_samples, s_samples).
        The covariance matrix of the betas generated.
    """

    cov = np.zeros((p, p))
    for i in range(p):
        for j in range(p):
            cov[i, j] = corr**(np.abs(i - j))
            
    return cov 


def gen_data(n, p, mean, cov, noise_var, beta0, centralize=False):

    """ Generates data used for testing COMBSS.

	Parameters
	----------
    n : integer
        The number of samples (i.e., rows of the design matrix X).

	p : integer
        The number of features (i.e., columns of the design matrix X).

    mean : float
       The mean of the multivariate normal distributed data.

    cov : float
       The covariance matrix of the multivariate normal distributed data.
    
    noise_var : float
       The variance of the additive noise.

    beta0 : array-like of float
       The true values of the coefficients vector

    centralize : Boolean
       Data is centralized if centralize = True, and not centralized if centralize = False.
       Default value: False.

       
	Returns
	-------
    X : array-like of shape (n, p)
		The design matrix, where `n` is the number of samples observed
		and `p` is the number of covariates measured in each sample.

	y : array-like of shape (n)
		The response data, where `n` is the number of response elements.
    """

    X = np.random.multivariate_normal(mean, cov, n)
    
    if centralize:
        # centralize X
        cmean = np.mean(X, axis=0)
        X = np.subtract(X, cmean)
        if (np.sum(X) == np.zeros(p)).all(): 
            print("Error: centralization didn't work")
            print(sys.path)
            sys.tracebacklimit = 1
            raise ValueError()
            
    y = [np.random.normal(X[i]@beta0, np.sqrt(noise_var)) for i in range(n)]
    y = np.array(y)
    return [X, y]



